"""Domain layer for Notees.

This package contains the core business logic of the application,
organized with clean architecture principles.

The domain layer is organized into:
- entities/: Domain objects with identity and lifecycle (Node, Property, Link, User)
- repositories/: Repository interfaces and implementations
- services/: Domain logic and business rules
- errors.py: Domain-specific exceptions

Architecture:
- Node is the core entity - everything is a node
- Pages are nodes tagged as "page"
- Blocks are nodes with a parent_id (always have page_id set)
- Tags are nodes tagged as "tag" (always also tagged as "page")
- Properties are stored in node_property + property_value_relation/property_value_scalar
- SuperTags: Tags can define which properties apply to tagged nodes
- Links are parsed from [[page]] and ((block)) references
"""

from .entities import (
    ALWAYS_SINGLE_TYPES,
    QUERY_PLACEHOLDERS,
    RELATION_TYPES,
    SCALAR_TYPES,
    AuthenticatedUser,
    BacklinkInfo,
    ChildBlock,
    ChildPathBlock,
    ClassBlock,
    ClassExtend,
    ClassProperty,
    ContainerBlock,
    ContentBlock,
    ContentOperator,
    Node,
    NodeCreateData,
    NodeLink,
    NodeProperty,
    NodeUpdateData,
    NodeView,
    NotBlock,
    ParentBlock,
    ParentPathBlock,
    Property,
    PropertyClassFilter,
    PropertyOperator,
    PropertyScope,
    PropertySelectionLine,
    PropertyType,
    PropertyValueRelation,
    PropertyValueScalar,
    PropertyValueSelection,
    QueryAST,
    QueryBlock,
    QueryBlockType,
    ReferenceBlock,
    ReferencePathBlock,
    User,
    UserCreateData,
    UserCredentials,
    UuidBlock,
    generate_uuid,
    utc_now_iso,
)
from .errors import (
    CircularReferenceError,
    DatePageDeletionError,
    DomainError,
    DuplicateEmailError,
    DuplicateNodeError,
    DuplicateWorkspaceError,
    InactiveUserError,
    InvalidCredentialsError,
    InvalidNodeHierarchyError,
    NodeError,
    NodeNotFoundError,
    NodeValidationError,
    OptimisticLockError,
    PermissionDeniedError,
    SyncConflictError,
    SyncError,
    SystemClassConstraintError,
    UserError,
    UserNotFoundError,
    WorkspaceError,
    WorkspaceNotFoundError,
)
from .services import (
    ClassManagementService,
    HierarchyService,
    LinkParsingService,
    NodeService,
    NodeViewService,
    QueryASTToSQL,
    QueryExecutor,
)

__all__ = [
    # Entities
    "Node",
    "NodeCreateData",
    "NodeUpdateData",
    "generate_uuid",
    "utc_now_iso",
    "BacklinkInfo",
    "NodeLink",
    "Property",
    "PropertyType",
    "PropertyScope",
    "PropertySelectionLine",
    "PropertyClassFilter",
    "ClassProperty",
    "NodeProperty",
    "PropertyValueScalar",
    "PropertyValueRelation",
    "PropertyValueSelection",
    "SCALAR_TYPES",
    "RELATION_TYPES",
    "ALWAYS_SINGLE_TYPES",
    "ClassExtend",
    "User",
    "UserCreateData",
    "UserCredentials",
    "AuthenticatedUser",
    "QueryBlockType",
    "PropertyOperator",
    "ContentOperator",
    "QueryBlock",
    "ContainerBlock",
    "NotBlock",
    "ClassBlock",
    "PropertyBlock",
    "ContentBlock",
    "ReferenceBlock",
    "ReferencePathBlock",
    "ParentBlock",
    "ParentPathBlock",
    "ChildBlock",
    "ChildPathBlock",
    "UuidBlock",
    "QueryAST",
    "NodeView",
    "QUERY_PLACEHOLDERS",
    # Errors
    "DomainError",
    "NodeError",
    "NodeNotFoundError",
    "DuplicateNodeError",
    "InvalidNodeHierarchyError",
    "NodeValidationError",
    "OptimisticLockError",
    "CircularReferenceError",
    "SystemClassConstraintError",
    "DatePageDeletionError",
    "UserError",
    "UserNotFoundError",
    "DuplicateEmailError",
    "InvalidCredentialsError",
    "InactiveUserError",
    "WorkspaceError",
    "WorkspaceNotFoundError",
    "DuplicateWorkspaceError",
    "PermissionDeniedError",
    "SyncError",
    "SyncConflictError",
    # Services
    "NodeService",
    "LinkParsingService",
    "HierarchyService",
    "QueryExecutor",
    "QueryASTToSQL",
    "NodeViewService",
    "ClassManagementService",
]
