"""Domain entities package."""

from .node import (
    Node,
    NodeCreateData,
    NodeUpdateData,
    generate_uuid,
    utc_now_iso,
)
from .property import (
    Property,
    PropertyType,
    PropertySelectionLine,
    PropertyClassFilter,
    ClassProperty,
    NodeProperty,
    PropertyValueScalar,
    PropertyValueRelation,
    PropertyValueSelection,
    SCALAR_TYPES,
    RELATION_TYPES,
    ALWAYS_SINGLE_TYPES,
)
from .link import (
    NodeLink,
    InlineClass,
    BacklinkInfo,
)
from .user import (
    User,
    UserCreateData,
    UserCredentials,
    AuthenticatedUser,
)
from .query import (
    QueryBlockType,
    PropertyOperator,
    ContentOperator,
    QueryBlock,
    ContainerBlock,
    NotBlock,
    ClassBlock,
    PropertyBlock,
    ContentBlock,
    ReferenceBlock,
    ReferencePathBlock,
    ParentBlock,
    ParentPathBlock,
    ChildBlock,
    ChildPathBlock,
    ClassPathBlock,
    UuidBlock,
    QueryAST,
    NodeView,
    QUERY_PLACEHOLDERS,
)

__all__ = [
    # Node
    "Node",
    "NodeCreateData",
    "NodeUpdateData",
    "generate_uuid",
    "utc_now_iso",
    # Property
    "Property",
    "PropertyType",
    "PropertySelectionLine",
    "PropertyClassFilter",
    "ClassProperty",
    "NodeProperty",
    "PropertyValueScalar",
    "PropertyValueRelation",
    "PropertyValueSelection",
    "SCALAR_TYPES",
    "RELATION_TYPES",
    "ALWAYS_SINGLE_TYPES",
    # Link
    "NodeLink",
    "InlineClass",
    # User
    "User",
    "UserCreateData",
    "UserCredentials",
    "AuthenticatedUser",
    # Query
    "QueryBlockType",
    "PropertyOperator",
    "ContentOperator",
    "QueryBlock",
    "ContainerBlock",
    "NotBlock",
    "ClassBlock",
    "PropertyBlock",
    "ContentBlock",
    "ReferenceBlock",
    "ReferencePathBlock",
    "ParentBlock",
    "ParentPathBlock",
    "ChildBlock",
    "ChildPathBlock",
    "ClassPathBlock",
    "UuidBlock",
    "QueryAST",
    "NodeView",
    "QUERY_PLACEHOLDERS",
]
