"""Node link entity.

Stores parsed links from node content for efficient backlink queries.
Links use the unified [[nodeId]] format for both pages and blocks.
Each node_link record has a uuid for unique identification.

Link sources can be:
1. Text links: Direct [[id]] syntax in a block's name field
   - source_id = the block T containing the link
   
2. Node-class property links: References via node-class properties
   - Stored via property_value_relation table, not node_link
   
The system property `classes` is excluded from backlinks entirely.

Inline class references (ref_type='class' in AST) are also stored in node_link
with is_inline_class=True.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

# Import from shared utility for consistency
from ...utils import utc_now


@dataclass
class NodeLink:
    """Represents a link from one node to another.
    
    All links use the unified [[nodeId]] format. The target node's
    is_page flag determines whether it's a page or block link.
    
    If is_tag is True, the link is a tag reference (displayed with #)
    rather than a regular [[link]].
    
    If is_inline_class is True, the link is an inline class reference
    (ref_type='class' in AST) rather than a regular node link.
    
    Schema fields:
    - source_id: Node containing the link
    - target_id: Referenced node
    - uuid: Unique identifier for this link record
    - position: Character position in the source node's content
    - is_tag: Whether this is a tag link
    - is_inline_class: Whether this is an inline class reference
    - create_date: When the link was created
    - create_uid: User who created the link
    """
    id: Optional[int] = None
    source_id: int = 0  # Node containing the link
    target_id: int = 0  # Referenced node
    uuid: Optional[str] = None  # UUID for this link record (provided by frontend or generated by DB)
    position: int = 0  # Character position in the source node's content
    is_tag: bool = False  # True if this is a tag reference (displayed with #)
    is_inline_class: bool = False  # True if this is an inline class reference
    name: Optional[str] = None  # Custom display text for the link
    create_date: datetime = field(default_factory=utc_now)
    create_uid: Optional[int] = None


@dataclass
class BacklinkInfo:
    """Extended backlink information with provenance for display.
    
    Contains all information needed to render a backlink with proper
    breadcrumbs showing property provenance.
    """
    link: NodeLink
    
    # Source information
    source_node_id: int  # The explicit linker (T for text, B for property)
    source_node_name: str
    source_node_uuid: str
    source_is_page: bool
    
    # Page context (for blocks)
    source_page_id: Optional[int] = None
    source_page_name: Optional[str] = None
    source_page_uuid: Optional[str] = None
    
    # Property provenance (for property links)
    property_id: Optional[int] = None
    property_name: Optional[str] = None
    
    # Text property context: if the link is inside a text property's
    # block hierarchy, this is the root block ID of the text property
    text_property_root_block_id: Optional[int] = None
    
    # Breadcrumb path from source to page ancestor
    # Format: [(node_id, name, is_property_segment), ...]
    # Property names are included as breadcrumb segments
    breadcrumb_path: list = field(default_factory=list)
