#!/usr/bin/env python3
"""One-way migration from the current Notees PostgreSQL schema to the ideal
operation-log + SQLite architecture.

The script is read-only against PostgreSQL. It emits operations into a local
SQLite file that can later be loaded into a workspace store.

Example (dry run against the dev database):
    uv run python scripts/migrate_to_ideal.py --dry-run

Example (write to a specific SQLite file):
    uv run python scripts/migrate_to_ideal.py --output data/migration/my_workspace.sqlite
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

from app.core.migration.assets import migrate_assets_for_workspace
from app.core.migration.connection import connect_postgres
from app.core.migration.links import (
    map_property_relation_targets,
    migrate_links_for_workspace,
)
from app.core.migration.nodes import (
    create_migration_context,
    migrate_nodes_for_workspace,
)
from app.core.migration.properties import migrate_properties_for_workspace
from app.core.migration.relay_writer import PostgresOperationWriter
from app.core.migration.writer import (
    InMemoryOperationWriter,
    OperationWriter,
    SqliteOperationWriter,
)
from app.core.uuid import uuidv7
from app.db.connection import setup_jsonb_codec


async def _fetch_workspace_ids(conn: Any) -> list[int]:
    """Return all active workspace integer ids ordered by id."""
    rows = await conn.fetch(
        "SELECT id FROM workspace WHERE active = TRUE ORDER BY id"
    )
    return [row["id"] for row in rows]


async def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Migrate Notees PostgreSQL data to the ideal operation log"
    )
    parser.add_argument(
        "--workspace-id",
        type=int,
        help="Migrate a single workspace by its legacy integer id",
    )
    parser.add_argument(
        "--output",
        type=str,
        help="Output SQLite file path (default: data/migration/ideal-<uuid>.sqlite)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print operations instead of writing to SQLite",
    )
    parser.add_argument(
        "--actor-id",
        type=str,
        help="Migration actor UUID (auto-generated by default)",
    )
    parser.add_argument(
        "--max-ops-print",
        type=int,
        default=20,
        help="Maximum operations to print per workspace in dry-run mode",
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        default=str(Path.home() / ".config" / "notees-backend-dev" / "data"),
        help="Base data directory containing workspace assets and the files/ tree",
    )
    parser.add_argument(
        "--skip-copy",
        action="store_true",
        help="Generate asset operations but do not copy blob files",
    )
    parser.add_argument(
        "--relay",
        action="store_true",
        help="Write operations directly to the PostgreSQL relay_envelope table",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Migrate even if the workspace already has relay envelopes",
    )
    args = parser.parse_args(argv)

    load_dotenv()

    actor_id = args.actor_id or uuidv7()
    physical_time = int(datetime.now(UTC).timestamp() * 1000)

    conn = await connect_postgres()
    await setup_jsonb_codec(conn)
    writer: OperationWriter
    try:
        if args.dry_run:
            writer = InMemoryOperationWriter()
            print("DRY RUN: operations will not be written")
        elif args.relay:
            writer = PostgresOperationWriter(conn)
            print("Writing operations directly to PostgreSQL relay_envelope")
        else:
            output_path = args.output or f"data/migration/ideal-{uuidv7()}.sqlite"
            writer = SqliteOperationWriter(output_path)
            print(f"Writing operations to {output_path}")

        workspace_ids = [args.workspace_id] if args.workspace_id else await _fetch_workspace_ids(conn)
        if not workspace_ids:
            print("No workspaces found to migrate.")
            return 0

        async def _flush() -> None:
            if isinstance(writer, PostgresOperationWriter):
                flushed = await writer.flush()
                if flushed:
                    print(f"  flushed {flushed} envelopes to relay")

        total_ops = 0
        for ws_id in workspace_ids:
            ctx = await create_migration_context(
                conn=conn,
                workspace_int_id=ws_id,
                actor_id=actor_id,
                physical_time=physical_time,
            )

            if args.relay and not args.force:
                existing = await writer.count_operations(ctx.workspace_uuid)
                if existing:
                    print(
                        f"Workspace {ws_id}: skipping, already has {existing} relay envelope(s)"
                    )
                    continue

            count = await migrate_nodes_for_workspace(
                conn=conn,
                workspace_int_id=ws_id,
                actor_id=actor_id,
                writer=writer,
                ctx=ctx,
            )
            total_ops += count
            print(f"Workspace {ws_id}: {count} node operations generated")
            await _flush()

            prop_ops = await migrate_properties_for_workspace(
                conn=conn,
                workspace_int_id=ws_id,
                ctx=ctx,
            )
            for op in prop_ops:
                writer.write_operation(op)
            total_ops += len(prop_ops)
            print(f"Workspace {ws_id}: {len(prop_ops)} property/class operations generated")
            await _flush()

            relation_targets = await map_property_relation_targets(
                conn=conn,
                workspace_int_id=ws_id,
                ctx=ctx,
            )
            if relation_targets:
                print(
                    f"Workspace {ws_id}: {len(relation_targets)} property relation targets mapped"
                )

            link_ops = await migrate_links_for_workspace(
                conn=conn,
                workspace_int_id=ws_id,
                ctx=ctx,
                writer=writer,
            )
            total_ops += link_ops
            print(f"Workspace {ws_id}: {link_ops} link operations generated")
            await _flush()

            asset_ops = await migrate_assets_for_workspace(
                conn=conn,
                workspace_int_id=ws_id,
                ctx=ctx,
                writer=writer,
                data_dir=Path(args.data_dir),
                copy_files=not args.skip_copy,
            )
            total_ops += asset_ops
            print(f"Workspace {ws_id}: {asset_ops} asset operations generated")
            await _flush()

            if args.dry_run:
                ops_in_workspace = count + len(prop_ops) + link_ops + asset_ops
                for idx, op in enumerate(writer.operations[-ops_in_workspace:]):
                    if idx >= args.max_ops_print:
                        remaining = ops_in_workspace - args.max_ops_print
                        print(f"    ... and {remaining} more")
                        break
                    print(f"    {op.envelope.op_type} {op.payload}")

        print(f"Total operations generated: {total_ops}")
    finally:
        if isinstance(writer, PostgresOperationWriter):
            await writer.aclose()
        else:
            writer.close()
        await conn.close()

    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
