import { chromium } from "playwright";
const NODE = process.env.PROBE_NODE_ID;
const browser = await chromium.launch({ headless: true });
const page = await (await browser.newContext({ viewport: { width: 1500, height: 950 } })).newPage();
page.on("pageerror", (e) => console.log("page error:", String(e).slice(0, 200)));
await page.goto("http://127.0.0.1:8378/login", { waitUntil: "commit", timeout: 60_000 });
const urlBox = page.getByRole("textbox", { name: /server url/i });
await urlBox.waitFor({ timeout: 30_000 });
await urlBox.fill("http://127.0.0.1:8377");
await page.getByRole("button", { name: /^continue$/i }).click();
await page.getByRole("textbox", { name: /email/i }).waitFor({ timeout: 15_000 });
await page.getByRole("textbox", { name: /email/i }).fill("miquelroselltarrago@gmail.com");
await page.getByRole("textbox", { name: /password/i }).fill(process.env.NOTEES_ADMIN_PASSWORD ?? "");
await page.getByRole("button", { name: /^sign in$/i }).click();
await page.waitForURL(/\/workspaces$/, { timeout: 20_000 });
// Enter the "Notas" workspace (the user's main one) so it becomes remembered.
await page.getByRole("button", { name: /open notas/i }).click();
await page.waitForSelector(".nt-topbar", { timeout: 40_000 });
await page.waitForTimeout(3000);
console.log("entered workspace, url:", page.url());
// Deep link to a node that lives in ANOTHER workspace ("Default").
await page.goto(`http://127.0.0.1:8378/${NODE}`);
await page.waitForTimeout(12000);
console.log("after deep link url:", page.url());
console.log("title:", await page.title());
const rememberedWs = await page.evaluate(() => localStorage.getItem("notees.workspaceId"));
console.log("remembered workspace now:", rememberedWs, "(Default =", process.env.PROBE_DEFAULT_WS + ")");
const nameVisible = await page.getByText("probe deeplink target", { exact: true }).first().isVisible();
console.log("node name visible:", nameVisible);
await page.screenshot({ path: "/tmp/deeplink.jpg", type: "jpeg", quality: 85 });
await browser.close();
