import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await (await browser.newContext({ viewport: { width: 1500, height: 950 } })).newPage();
await page.goto("http://localhost:8378/login", { waitUntil: "commit", timeout: 60_000 });
const urlBox = page.getByRole("textbox", { name: /server url/i });
await urlBox.waitFor({ timeout: 30_000 });
await urlBox.fill("http://localhost:8377");
await page.getByRole("button", { name: /^continue$/i }).click();
await page.getByRole("textbox", { name: /email/i }).waitFor({ timeout: 15_000 });
await page.getByRole("textbox", { name: /email/i }).fill("miquelroselltarrago@gmail.com");
await page.getByRole("textbox", { name: /password/i }).fill(process.env.NOTEES_ADMIN_PASSWORD ?? "");
await page.getByRole("button", { name: /^sign in$/i }).click();
await page.waitForURL(/\/workspaces$/, { timeout: 20_000 });
await page.waitForTimeout(1200);
console.log("url after login:", page.url());
console.log("fullscreen view:", await page.locator(".workspaces-view").isVisible());
console.log("cards:", await page.locator(".workspace-management__card").count());
await page.screenshot({ path: "/tmp/workspaces-view.jpg", type: "jpeg", quality: 85 });
// Enter the first workspace
await page.getByRole("button", { name: /open /i }).first().click();
await page.waitForTimeout(11000);
console.log("url after enter:", page.url());
console.log("app shell:", await page.locator(".nt-topbar").isVisible());
await browser.close();
