// Auto-generated MDI icon map — do not edit manually
// This file replaces dynamic namespace imports to enable tree-shaking

import {
  mdiAccountCircle,
  mdiAccountOutline,
  mdiAlarm,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiAlphaD,
  mdiAlphaM,
  mdiAlphaQ,
  mdiAlphaS,
  mdiAlphaY,
  mdiArchive,
  mdiArchiveOutline,
  mdiArrangeBringToFront,
  mdiArrangeSendToBack,
  mdiArrowCollapse,
  mdiArrowDown,
  mdiArrowDownBold,
  mdiArrowExpand,
  mdiArrowExpandHorizontal,
  mdiArrowLeft,
  mdiArrowLeftBold,
  mdiArrowRight,
  mdiArrowRightBold,
  mdiArrowUp,
  mdiArrowUpBold,
  mdiAsterisk,
  mdiAtom,
  mdiAutoFix,
  mdiBackupRestore,
  mdiBell,
  mdiBellOutline,
  mdiBellRing,
  mdiBluetooth,
  mdiBook,
  mdiBookOpenPageVariant,
  mdiBookOutline,
  mdiBookmark,
  mdiBookmarkOutline,
  mdiBrain,
  mdiCalendar,
  mdiCalendarEnd,
  mdiCalendarMonth,
  mdiCalendarOutline,
  mdiCalendarRange,
  mdiCalendarStart,
  mdiCalendarToday,
  mdiCalendarWeek,
  mdiCallMade,
  mdiCallReceived,
  mdiCamera,
  mdiCameraOutline,
  mdiCardOutline,
  mdiCardPlusOutline,
  mdiCellphone,
  mdiChartGantt,
  mdiChat,
  mdiChatOutline,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarkedCircleOutline,
  mdiCheckboxMarkedOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircleOutline,
  mdiCircleSmall,
  mdiClipboardTextOutline,
  mdiClock,
  mdiClockOutline,
  mdiClockTimeEight,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCloud,
  mdiCloudOutline,
  mdiCodeBraces,
  mdiCodeJson,
  mdiCodeTags,
  mdiCog,
  mdiCogOutline,
  mdiComment,
  mdiCommentOutline,
  mdiCommentTextOutline,
  mdiCompass,
  mdiCompassOutline,
  mdiConnection,
  mdiContentCopy,
  mdiContentCut,
  mdiContentDuplicate,
  mdiContentPaste,
  mdiContentSave,
  mdiContentSaveOutline,
  mdiCrosshairsGps,
  mdiCubeOutline,
  mdiCursorDefaultOutline,
  mdiCursorPointer,
  mdiDatabase,
  mdiDatabaseOutline,
  mdiDatabaseRefresh,
  mdiDecimal,
  mdiDelete,
  mdiDeleteOutline,
  mdiDistributeHorizontalCenter,
  mdiDockLeft,
  mdiDockRight,
  mdiDockTop,
  mdiDotsHorizontal,
  mdiDotsVertical,
  mdiDownload,
  mdiDownloadOutline,
  mdiDrag,
  mdiEarth,
  mdiEmail,
  mdiEmailOutline,
  mdiEraserVariant,
  mdiExport,
  mdiEye,
  mdiEyeOff,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFile,
  mdiFileChartOutline,
  mdiFileCloud,
  mdiFileDocument,
  mdiFileDocumentEditOutline,
  mdiFileDocumentMultipleOutline,
  mdiFileDocumentOutline,
  mdiFileDownload,
  mdiFileExport,
  mdiFileFind,
  mdiFileImageOutline,
  mdiFileImport,
  mdiFileMultiple,
  mdiFileMusicOutline,
  mdiFileOutline,
  mdiFilePdfBox,
  mdiFilePlus,
  mdiFileTree,
  mdiFileTreeOutline,
  mdiFileUpload,
  mdiFileVideoOutline,
  mdiFilter,
  mdiFilterOutline,
  mdiFingerprint,
  mdiFitToScreen,
  mdiFlag,
  mdiFlagOutline,
  mdiFolder,
  mdiFolderOpenOutline,
  mdiFolderOutline,
  mdiFormatAlignCenter,
  mdiFormatAlignLeft,
  mdiFormatAlignRight,
  mdiFormatBold,
  mdiFormatColorFill,
  mdiFormatColorText,
  mdiFormatIndentDecrease,
  mdiFormatIndentIncrease,
  mdiFormatItalic,
  mdiFormatLetterCaseUpper,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatListNumberedRtl,
  mdiFormatQuoteClose,
  mdiFormatSize,
  mdiFormatStrikethrough,
  mdiFormatText,
  mdiFormatUnderline,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiGift,
  mdiGiftOutline,
  mdiGraphOutline,
  mdiGrid,
  mdiGroup,
  mdiHeart,
  mdiHeartOutline,
  mdiHexagonOutline,
  mdiHistory,
  mdiHome,
  mdiHomeOutline,
  mdiImage,
  mdiImageOutline,
  mdiImagePlus,
  mdiImport,
  mdiInbox,
  mdiKey,
  mdiKeyOutline,
  mdiKeyboard,
  mdiLaptop,
  mdiLightbulb,
  mdiLightbulbOutline,
  mdiLink,
  mdiLinkOff,
  mdiLinkVariant,
  mdiLinkVariantOff,
  mdiLock,
  mdiLockOpen,
  mdiLockOpenOutline,
  mdiLockOutline,
  mdiLogout,
  mdiMagnet,
  mdiMagnify,
  mdiMap,
  mdiMapMarker,
  mdiMapMarkerOutline,
  mdiMapOutline,
  mdiMarker,
  mdiMenu,
  mdiMenuDown,
  mdiMenuLeft,
  mdiMenuRight,
  mdiMenuUp,
  mdiMerge,
  mdiMessage,
  mdiMessageOutline,
  mdiMinus,
  mdiMonitor,
  mdiMouse,
  mdiMusic,
  mdiMusicNote,
  mdiMusicNoteOutline,
  mdiNavigation,
  mdiNewspaper,
  mdiNote,
  mdiNoteTextOutline,
  mdiNotebook,
  mdiNotebookOutline,
  mdiNumeric1,
  mdiNumeric2,
  mdiNumeric3,
  mdiNumeric9Plus,
  mdiPalette,
  mdiPaperclip,
  mdiPauseCircle,
  mdiPencil,
  mdiPencilOutline,
  mdiPhone,
  mdiPhoneOutline,
  mdiPin,
  mdiPinOff,
  mdiPinOutline,
  mdiPlayCircle,
  mdiPlus,
  mdiPlusBox,
  mdiPound,
  mdiPrinter,
  mdiRectangleOutline,
  mdiRedo,
  mdiRefresh,
  mdiReload,
  mdiReply,
  mdiRestore,
  mdiScaleBalance,
  mdiSchool,
  mdiSecurity,
  mdiSend,
  mdiSendOutline,
  mdiServer,
  mdiServerNetwork,
  mdiSetAll,
  mdiSetNone,
  mdiShapeOutline,
  mdiShare,
  mdiShareOutline,
  mdiShareVariant,
  mdiShareVariantOutline,
  mdiShield,
  mdiShieldOutline,
  mdiShuffle,
  mdiSort,
  mdiSortVariant,
  mdiSquareEditOutline,
  mdiStar,
  mdiStarOutline,
  mdiStopCircle,
  mdiSwapHorizontal,
  mdiSync,
  mdiTable,
  mdiTableOfContents,
  mdiTablePlus,
  mdiTablet,
  mdiTag,
  mdiTagMultipleOutline,
  mdiTagOff,
  mdiTagOutline,
  mdiText,
  mdiTextBox,
  mdiTextBoxMultipleOutline,
  mdiTextBoxOutline,
  mdiTextShort,
  mdiThumbDown,
  mdiThumbDownOutline,
  mdiThumbUp,
  mdiThumbUpOutline,
  mdiTimelineClockOutline,
  mdiTimer,
  mdiTimerOutline,
  mdiTrashCan,
  mdiTrashCanOutline,
  mdiTrayArrowDown,
  mdiTriangleOutline,
  mdiTrophy,
  mdiTrophyOutline,
  mdiTune,
  mdiUndo,
  mdiUngroup,
  mdiUploadOutline,
  mdiUsb,
  mdiVectorLine,
  mdiVectorPolygon,
  mdiVideo,
  mdiVideoOutline,
  mdiViewColumn,
  mdiViewCompact,
  mdiViewDashboard,
  mdiViewGrid,
  mdiViewGridOutline,
  mdiViewHeadline,
  mdiViewList,
  mdiViewModule,
  mdiVolumeHigh,
  mdiVolumeMute,
  mdiWeatherCloudy,
  mdiWeatherFog,
  mdiWeatherLightning,
  mdiWeatherNight,
  mdiWeatherPartlyCloudy,
  mdiWeatherRainy,
  mdiWeatherSnowy,
  mdiWeatherSunny,
  mdiWeb,
  mdiWeight,
  mdiWifi,
  mdiWifiOff,
  mdiWindowMaximize,
  mdiWindowMinimize,
} from "@mdi/js";

export const MDI_ICON_MAP: Record<string, string> = {
  mdiAccountCircle: mdiAccountCircle,
  mdiAccountOutline: mdiAccountOutline,
  mdiAlarm: mdiAlarm,
  mdiAlertCircle: mdiAlertCircle,
  mdiAlertCircleOutline: mdiAlertCircleOutline,
  mdiAlertOutline: mdiAlertOutline,
  mdiAlphaD: mdiAlphaD,
  mdiAlphaM: mdiAlphaM,
  mdiAlphaQ: mdiAlphaQ,
  mdiAlphaS: mdiAlphaS,
  mdiAlphaY: mdiAlphaY,
  mdiArchive: mdiArchive,
  mdiArchiveOutline: mdiArchiveOutline,
  mdiArrangeBringToFront: mdiArrangeBringToFront,
  mdiArrangeSendToBack: mdiArrangeSendToBack,
  mdiArrowCollapse: mdiArrowCollapse,
  mdiArrowDown: mdiArrowDown,
  mdiArrowDownBold: mdiArrowDownBold,
  mdiArrowExpand: mdiArrowExpand,
  mdiArrowExpandHorizontal: mdiArrowExpandHorizontal,
  mdiArrowLeft: mdiArrowLeft,
  mdiArrowLeftBold: mdiArrowLeftBold,
  mdiArrowRight: mdiArrowRight,
  mdiArrowRightBold: mdiArrowRightBold,
  mdiArrowUp: mdiArrowUp,
  mdiArrowUpBold: mdiArrowUpBold,
  mdiAsterisk: mdiAsterisk,
  mdiAtom: mdiAtom,
  mdiAutoFix: mdiAutoFix,
  mdiBackupRestore: mdiBackupRestore,
  mdiBell: mdiBell,
  mdiBellOutline: mdiBellOutline,
  mdiBellRing: mdiBellRing,
  mdiBluetooth: mdiBluetooth,
  mdiBook: mdiBook,
  mdiBookOpenPageVariant: mdiBookOpenPageVariant,
  mdiBookOutline: mdiBookOutline,
  mdiBookmark: mdiBookmark,
  mdiBookmarkOutline: mdiBookmarkOutline,
  mdiBrain: mdiBrain,
  mdiCalendar: mdiCalendar,
  mdiCalendarEnd: mdiCalendarEnd,
  mdiCalendarMonth: mdiCalendarMonth,
  mdiCalendarOutline: mdiCalendarOutline,
  mdiCalendarRange: mdiCalendarRange,
  mdiCalendarStart: mdiCalendarStart,
  mdiCalendarToday: mdiCalendarToday,
  mdiCalendarWeek: mdiCalendarWeek,
  mdiCallMade: mdiCallMade,
  mdiCallReceived: mdiCallReceived,
  mdiCamera: mdiCamera,
  mdiCameraOutline: mdiCameraOutline,
  mdiCardOutline: mdiCardOutline,
  mdiCardPlusOutline: mdiCardPlusOutline,
  mdiCellphone: mdiCellphone,
  mdiChartGantt: mdiChartGantt,
  mdiChat: mdiChat,
  mdiChatOutline: mdiChatOutline,
  mdiCheck: mdiCheck,
  mdiCheckCircle: mdiCheckCircle,
  mdiCheckCircleOutline: mdiCheckCircleOutline,
  mdiCheckboxBlankOutline: mdiCheckboxBlankOutline,
  mdiCheckboxMarkedCircleOutline: mdiCheckboxMarkedCircleOutline,
  mdiCheckboxMarkedOutline: mdiCheckboxMarkedOutline,
  mdiChevronDown: mdiChevronDown,
  mdiChevronLeft: mdiChevronLeft,
  mdiChevronRight: mdiChevronRight,
  mdiChevronUp: mdiChevronUp,
  mdiCircleOutline: mdiCircleOutline,
  mdiCircleSmall: mdiCircleSmall,
  mdiClipboardTextOutline: mdiClipboardTextOutline,
  mdiClock: mdiClock,
  mdiClockOutline: mdiClockOutline,
  mdiClockTimeEight: mdiClockTimeEight,
  mdiClose: mdiClose,
  mdiCloseCircle: mdiCloseCircle,
  mdiCloseCircleOutline: mdiCloseCircleOutline,
  mdiCloud: mdiCloud,
  mdiCloudOutline: mdiCloudOutline,
  mdiCodeBraces: mdiCodeBraces,
  mdiCodeJson: mdiCodeJson,
  mdiCodeTags: mdiCodeTags,
  mdiCog: mdiCog,
  mdiCogOutline: mdiCogOutline,
  mdiComment: mdiComment,
  mdiCommentOutline: mdiCommentOutline,
  mdiCommentTextOutline: mdiCommentTextOutline,
  mdiCompass: mdiCompass,
  mdiCompassOutline: mdiCompassOutline,
  mdiConnection: mdiConnection,
  mdiContentCopy: mdiContentCopy,
  mdiContentCut: mdiContentCut,
  mdiContentDuplicate: mdiContentDuplicate,
  mdiContentPaste: mdiContentPaste,
  mdiContentSave: mdiContentSave,
  mdiContentSaveOutline: mdiContentSaveOutline,
  mdiCrosshairsGps: mdiCrosshairsGps,
  mdiCubeOutline: mdiCubeOutline,
  mdiCursorDefaultOutline: mdiCursorDefaultOutline,
  mdiCursorPointer: mdiCursorPointer,
  mdiDatabase: mdiDatabase,
  mdiDatabaseOutline: mdiDatabaseOutline,
  mdiDatabaseRefresh: mdiDatabaseRefresh,
  mdiDecimal: mdiDecimal,
  mdiDelete: mdiDelete,
  mdiDeleteOutline: mdiDeleteOutline,
  mdiDistributeHorizontalCenter: mdiDistributeHorizontalCenter,
  mdiDockLeft: mdiDockLeft,
  mdiDockRight: mdiDockRight,
  mdiDockTop: mdiDockTop,
  mdiDotsHorizontal: mdiDotsHorizontal,
  mdiDotsVertical: mdiDotsVertical,
  mdiDownload: mdiDownload,
  mdiDownloadOutline: mdiDownloadOutline,
  mdiDrag: mdiDrag,
  mdiEarth: mdiEarth,
  mdiEmail: mdiEmail,
  mdiEmailOutline: mdiEmailOutline,
  mdiEraserVariant: mdiEraserVariant,
  mdiExport: mdiExport,
  mdiEye: mdiEye,
  mdiEyeOff: mdiEyeOff,
  mdiEyeOffOutline: mdiEyeOffOutline,
  mdiEyeOutline: mdiEyeOutline,
  mdiFile: mdiFile,
  mdiFileChartOutline: mdiFileChartOutline,
  mdiFileCloud: mdiFileCloud,
  mdiFileDocument: mdiFileDocument,
  mdiFileDocumentEditOutline: mdiFileDocumentEditOutline,
  mdiFileDocumentMultipleOutline: mdiFileDocumentMultipleOutline,
  mdiFileDocumentOutline: mdiFileDocumentOutline,
  mdiFileDownload: mdiFileDownload,
  mdiFileExport: mdiFileExport,
  mdiFileFind: mdiFileFind,
  mdiFileImageOutline: mdiFileImageOutline,
  mdiFileImport: mdiFileImport,
  mdiFileMultiple: mdiFileMultiple,
  mdiFileMusicOutline: mdiFileMusicOutline,
  mdiFileOutline: mdiFileOutline,
  mdiFilePdfBox: mdiFilePdfBox,
  mdiFilePlus: mdiFilePlus,
  mdiFileTree: mdiFileTree,
  mdiFileTreeOutline: mdiFileTreeOutline,
  mdiFileUpload: mdiFileUpload,
  mdiFileVideoOutline: mdiFileVideoOutline,
  mdiFilter: mdiFilter,
  mdiFilterOutline: mdiFilterOutline,
  mdiFingerprint: mdiFingerprint,
  mdiFitToScreen: mdiFitToScreen,
  mdiFlag: mdiFlag,
  mdiFlagOutline: mdiFlagOutline,
  mdiFolder: mdiFolder,
  mdiFolderOpenOutline: mdiFolderOpenOutline,
  mdiFolderOutline: mdiFolderOutline,
  mdiFormatAlignCenter: mdiFormatAlignCenter,
  mdiFormatAlignLeft: mdiFormatAlignLeft,
  mdiFormatAlignRight: mdiFormatAlignRight,
  mdiFormatBold: mdiFormatBold,
  mdiFormatColorFill: mdiFormatColorFill,
  mdiFormatColorText: mdiFormatColorText,
  mdiFormatIndentDecrease: mdiFormatIndentDecrease,
  mdiFormatIndentIncrease: mdiFormatIndentIncrease,
  mdiFormatItalic: mdiFormatItalic,
  mdiFormatLetterCaseUpper: mdiFormatLetterCaseUpper,
  mdiFormatListBulleted: mdiFormatListBulleted,
  mdiFormatListNumbered: mdiFormatListNumbered,
  mdiFormatListNumberedRtl: mdiFormatListNumberedRtl,
  mdiFormatQuoteClose: mdiFormatQuoteClose,
  mdiFormatSize: mdiFormatSize,
  mdiFormatStrikethrough: mdiFormatStrikethrough,
  mdiFormatText: mdiFormatText,
  mdiFormatUnderline: mdiFormatUnderline,
  mdiFullscreen: mdiFullscreen,
  mdiFullscreenExit: mdiFullscreenExit,
  mdiGift: mdiGift,
  mdiGiftOutline: mdiGiftOutline,
  mdiGraphOutline: mdiGraphOutline,
  mdiGrid: mdiGrid,
  mdiGroup: mdiGroup,
  mdiHeart: mdiHeart,
  mdiHeartOutline: mdiHeartOutline,
  mdiHexagonOutline: mdiHexagonOutline,
  mdiHistory: mdiHistory,
  mdiHome: mdiHome,
  mdiHomeOutline: mdiHomeOutline,
  mdiImage: mdiImage,
  mdiImageOutline: mdiImageOutline,
  mdiImagePlus: mdiImagePlus,
  mdiImport: mdiImport,
  mdiInbox: mdiInbox,
  mdiKey: mdiKey,
  mdiKeyOutline: mdiKeyOutline,
  mdiKeyboard: mdiKeyboard,
  mdiLaptop: mdiLaptop,
  mdiLightbulb: mdiLightbulb,
  mdiLightbulbOutline: mdiLightbulbOutline,
  mdiLink: mdiLink,
  mdiLinkOff: mdiLinkOff,
  mdiLinkVariant: mdiLinkVariant,
  mdiLinkVariantOff: mdiLinkVariantOff,
  mdiLock: mdiLock,
  mdiLockOpen: mdiLockOpen,
  mdiLockOpenOutline: mdiLockOpenOutline,
  mdiLockOutline: mdiLockOutline,
  mdiLogout: mdiLogout,
  mdiMagnet: mdiMagnet,
  mdiMagnify: mdiMagnify,
  mdiMap: mdiMap,
  mdiMapMarker: mdiMapMarker,
  mdiMapMarkerOutline: mdiMapMarkerOutline,
  mdiMapOutline: mdiMapOutline,
  mdiMarker: mdiMarker,
  mdiMenu: mdiMenu,
  mdiMenuDown: mdiMenuDown,
  mdiMenuLeft: mdiMenuLeft,
  mdiMenuRight: mdiMenuRight,
  mdiMenuUp: mdiMenuUp,
  mdiMerge: mdiMerge,
  mdiMessage: mdiMessage,
  mdiMessageOutline: mdiMessageOutline,
  mdiMinus: mdiMinus,
  mdiMonitor: mdiMonitor,
  mdiMouse: mdiMouse,
  mdiMusic: mdiMusic,
  mdiMusicNote: mdiMusicNote,
  mdiMusicNoteOutline: mdiMusicNoteOutline,
  mdiNavigation: mdiNavigation,
  mdiNewspaper: mdiNewspaper,
  mdiNote: mdiNote,
  mdiNoteTextOutline: mdiNoteTextOutline,
  mdiNotebook: mdiNotebook,
  mdiNotebookOutline: mdiNotebookOutline,
  mdiNumeric1: mdiNumeric1,
  mdiNumeric2: mdiNumeric2,
  mdiNumeric3: mdiNumeric3,
  mdiNumeric9Plus: mdiNumeric9Plus,
  mdiPalette: mdiPalette,
  mdiPaperclip: mdiPaperclip,
  mdiPauseCircle: mdiPauseCircle,
  mdiPencil: mdiPencil,
  mdiPencilOutline: mdiPencilOutline,
  mdiPhone: mdiPhone,
  mdiPhoneOutline: mdiPhoneOutline,
  mdiPin: mdiPin,
  mdiPinOff: mdiPinOff,
  mdiPinOutline: mdiPinOutline,
  mdiPlayCircle: mdiPlayCircle,
  mdiPlus: mdiPlus,
  mdiPlusBox: mdiPlusBox,
  mdiPound: mdiPound,
  mdiPrinter: mdiPrinter,
  mdiRectangleOutline: mdiRectangleOutline,
  mdiRedo: mdiRedo,
  mdiRefresh: mdiRefresh,
  mdiReload: mdiReload,
  mdiReply: mdiReply,
  mdiRestore: mdiRestore,
  mdiScaleBalance: mdiScaleBalance,
  mdiSchool: mdiSchool,
  mdiSecurity: mdiSecurity,
  mdiSend: mdiSend,
  mdiSendOutline: mdiSendOutline,
  mdiServer: mdiServer,
  mdiServerNetwork: mdiServerNetwork,
  mdiSetAll: mdiSetAll,
  mdiSetNone: mdiSetNone,
  mdiShapeOutline: mdiShapeOutline,
  mdiShare: mdiShare,
  mdiShareOutline: mdiShareOutline,
  mdiShareVariant: mdiShareVariant,
  mdiShareVariantOutline: mdiShareVariantOutline,
  mdiShield: mdiShield,
  mdiShieldOutline: mdiShieldOutline,
  mdiShuffle: mdiShuffle,
  mdiSort: mdiSort,
  mdiSortVariant: mdiSortVariant,
  mdiSquareEditOutline: mdiSquareEditOutline,
  mdiStar: mdiStar,
  mdiStarOutline: mdiStarOutline,
  mdiStopCircle: mdiStopCircle,
  mdiSwapHorizontal: mdiSwapHorizontal,
  mdiSync: mdiSync,
  mdiTable: mdiTable,
  mdiTableOfContents: mdiTableOfContents,
  mdiTablePlus: mdiTablePlus,
  mdiTablet: mdiTablet,
  mdiTag: mdiTag,
  mdiTagMultipleOutline: mdiTagMultipleOutline,
  mdiTagOff: mdiTagOff,
  mdiTagOutline: mdiTagOutline,
  mdiText: mdiText,
  mdiTextBox: mdiTextBox,
  mdiTextBoxMultipleOutline: mdiTextBoxMultipleOutline,
  mdiTextBoxOutline: mdiTextBoxOutline,
  mdiTextShort: mdiTextShort,
  mdiThumbDown: mdiThumbDown,
  mdiThumbDownOutline: mdiThumbDownOutline,
  mdiThumbUp: mdiThumbUp,
  mdiThumbUpOutline: mdiThumbUpOutline,
  mdiTimelineClockOutline: mdiTimelineClockOutline,
  mdiTimer: mdiTimer,
  mdiTimerOutline: mdiTimerOutline,
  mdiTrashCan: mdiTrashCan,
  mdiTrashCanOutline: mdiTrashCanOutline,
  mdiTrayArrowDown: mdiTrayArrowDown,
  mdiTriangleOutline: mdiTriangleOutline,
  mdiTrophy: mdiTrophy,
  mdiTrophyOutline: mdiTrophyOutline,
  mdiTune: mdiTune,
  mdiUndo: mdiUndo,
  mdiUngroup: mdiUngroup,
  mdiUploadOutline: mdiUploadOutline,
  mdiUsb: mdiUsb,
  mdiVectorLine: mdiVectorLine,
  mdiVectorPolygon: mdiVectorPolygon,
  mdiVideo: mdiVideo,
  mdiVideoOutline: mdiVideoOutline,
  mdiViewColumn: mdiViewColumn,
  mdiViewCompact: mdiViewCompact,
  mdiViewDashboard: mdiViewDashboard,
  mdiViewGrid: mdiViewGrid,
  mdiViewGridOutline: mdiViewGridOutline,
  mdiViewHeadline: mdiViewHeadline,
  mdiViewList: mdiViewList,
  mdiViewModule: mdiViewModule,
  mdiVolumeHigh: mdiVolumeHigh,
  mdiVolumeMute: mdiVolumeMute,
  mdiWeatherCloudy: mdiWeatherCloudy,
  mdiWeatherFog: mdiWeatherFog,
  mdiWeatherLightning: mdiWeatherLightning,
  mdiWeatherNight: mdiWeatherNight,
  mdiWeatherPartlyCloudy: mdiWeatherPartlyCloudy,
  mdiWeatherRainy: mdiWeatherRainy,
  mdiWeatherSnowy: mdiWeatherSnowy,
  mdiWeatherSunny: mdiWeatherSunny,
  mdiWeb: mdiWeb,
  mdiWeight: mdiWeight,
  mdiWifi: mdiWifi,
  mdiWifiOff: mdiWifiOff,
  mdiWindowMaximize: mdiWindowMaximize,
  mdiWindowMinimize: mdiWindowMinimize,
};

export function getMdiIconPath(name: string): string | null {
  return MDI_ICON_MAP[name] || null;
}
