import {
  mdiAccountCircle, mdiAccountCog, mdiAccountGroupOutline, mdiAlertCircle,
  mdiAlertCircleOutline, mdiAlertOctagonOutline, mdiAlertOutline, mdiAlignHorizontalCenter,
  mdiAlignHorizontalLeft, mdiAlignHorizontalRight, mdiAlignVerticalBottom, mdiAlignVerticalCenter,
  mdiAlignVerticalTop, mdiAlphaD, mdiAlphaM, mdiAlphaQ,
  mdiAlphaS, mdiAlphaY, mdiArchive, mdiArchiveArrowDownOutline,
  mdiArchiveArrowUp, mdiArchiveArrowUpOutline, mdiArchiveOutline, mdiArrangeBringToFront,
  mdiArrangeSendToBack, mdiArrowExpandHorizontal, mdiArrowLeft, mdiArrowRight,
  mdiAsterisk, mdiAtom, mdiAutoFix, mdiBackupRestore,
  mdiBook, mdiBookOpenPageVariant, mdiBookOpenVariant, mdiBrain,
  mdiCalendar, mdiCalendarAlert, mdiCalendarArrowRight, mdiCalendarCheck,
  mdiCalendarClock, mdiCalendarEnd, mdiCalendarMonth, mdiCalendarRange,
  mdiCalendarStart, mdiCalendarToday, mdiCallMade, mdiCallReceived,
  mdiCardOutline, mdiCardPlusOutline, mdiChartBar, mdiChartGantt,
  mdiChartPie, mdiCheck, mdiCheckboxBlankOutline, mdiCheckboxMarkedCircleOutline,
  mdiCheckboxMarkedOutline, mdiCheckCircleOutline, mdiChevronDown, mdiChevronLeft,
  mdiChevronRight, mdiChevronUp, mdiCircleOutline, mdiCircleSmall,
  mdiClipboardTextOutline, mdiClockOutline, mdiClose, mdiCloseCircleOutline,
  mdiCloudOutline, mdiCodeBraces, mdiCodeJson, mdiCodeTags,
  mdiCog, mdiCogOutline, mdiCommentOutline, mdiCommentTextOutline,
  mdiConnection, mdiContentCopy, mdiContentDuplicate, mdiContentPaste,
  mdiCrosshairsGps, mdiCubeOutline, mdiCursorDefaultOutline, mdiCursorPointer,
  mdiDatabaseOutline, mdiDatabaseRefresh, mdiDelete, mdiDeleteForeverOutline,
  mdiDeleteOutline, mdiDeleteSweep, mdiDistributeHorizontalCenter, mdiDistributeVerticalCenter,
  mdiDockLeft, mdiDockRight, mdiDockTop, mdiDotsHorizontal,
  mdiDotsVertical, mdiDownload, mdiDrag, mdiDragVertical,
  mdiEmoticonHappyOutline, mdiEraserVariant, mdiExport, mdiEye,
  mdiEyeOff, mdiEyeOutline, mdiFeather, mdiFileChartOutline,
  mdiFileDocumentMultipleOutline, mdiFileDocumentOutline, mdiFileMultiple, mdiFileTree,
  mdiFileTreeOutline, mdiFilter, mdiFilterOutline, mdiFingerprint,
  mdiFitToScreen, mdiFolderMoveOutline, mdiFolderOpenOutline, mdiFolderOutline,
  mdiFormatBold, mdiFormatHeaderPound, mdiFormatItalic, mdiFormatLetterCaseUpper,
  mdiFormatListBulleted, mdiFormatListCheckbox, mdiFormatListNumbered, mdiFormatListNumberedRtl,
  mdiFormatQuoteOpen, mdiFormatStrikethrough, mdiFormatText, mdiFormatUnderline,
  mdiFullscreen, mdiGraphOutline, mdiGrid, mdiGroup,
  mdiHeartOutline, mdiHelpCircle, mdiHexagonOutline, mdiHistory,
  mdiHome, mdiShapeOutline, mdiIdentifier, mdiImageOutline,
  mdiImagePlus, mdiImport, mdiInbox, mdiInboxArrowDown,
  mdiLightbulbOnOutline, mdiLink, mdiLinkOff, mdiLinkVariant,
  mdiLock, mdiLockOpenOutline, mdiLockOutline, mdiLogout,
  mdiMagnet, mdiMagnify, mdiMap, mdiMapOutline,
  mdiMarker, mdiMenu, mdiMerge, mdiMinus,
  mdiMonitor, mdiMusicNoteOutline, mdiNewspaper, mdiNote,
  mdiNotebookOutline, mdiNoteTextOutline, mdiNumeric1, mdiNumeric2,
  mdiNumeric3, mdiNumeric9Plus, mdiOpenInApp, mdiOpenInNew,
  mdiPalette, mdiPaperclip, mdiRectangleOutline, mdiPencil,
  mdiPencilOutline, mdiPin, mdiPinOff, mdiPinOutline,
  mdiPlus, mdiPlusBox, mdiPlusBoxOutline, mdiPresentationPlay,
  mdiQrcode, mdiRedo, mdiRefresh, mdiReply,
  mdiRestore, mdiRhombusOutline, mdiScaleBalance, mdiSchool,
  mdiSelectAll, mdiSend, mdiServerNetwork, mdiSetAll,
  mdiSetNone, mdiShareVariant, mdiShareVariantOutline, mdiShuffle,
  mdiStar, mdiStarOutline, mdiSwapHorizontal, mdiSync,
  mdiTable, mdiTableOfContents, mdiTablePlus, mdiTag,
  mdiTagMultiple, mdiTagMultipleOutline, mdiTagOff, mdiTagOutline,
  mdiTarget, mdiText, mdiTextBox, mdiTextBoxMultipleOutline,
  mdiTextBoxOutline, mdiTextShort, mdiTimelineClockOutline, mdiTrashCan,
  mdiTrashCanOutline, mdiTrayArrowDown, mdiTriangleOutline, mdiTune,
  mdiUndo, mdiUngroup, mdiVectorLine, mdiVectorPolygon,
  mdiViewColumn, mdiViewCompact, mdiViewDashboard, mdiViewDashboardOutline,
  mdiViewGrid, mdiViewHeadline, mdiWeatherNight, mdiWeatherSunny,
  mdiWeb, mdiWeight, mdiWhiteBalanceSunny, mdiWifi,
  mdiWifiOff
} from "@mdi/js";

export const mdiPathMap: Record<string, string> = {
  'account-circle': mdiAccountCircle,
  'account-cog': mdiAccountCog,
  'account-group-outline': mdiAccountGroupOutline,
  'alert-circle': mdiAlertCircle,
  'alert-circle-outline': mdiAlertCircleOutline,
  'alert-octagon-outline': mdiAlertOctagonOutline,
  'alert-outline': mdiAlertOutline,
  'align-horizontal-center': mdiAlignHorizontalCenter,
  'align-horizontal-left': mdiAlignHorizontalLeft,
  'align-horizontal-right': mdiAlignHorizontalRight,
  'align-vertical-bottom': mdiAlignVerticalBottom,
  'align-vertical-center': mdiAlignVerticalCenter,
  'align-vertical-top': mdiAlignVerticalTop,
  'alpha-d': mdiAlphaD,
  'alpha-m': mdiAlphaM,
  'alpha-q': mdiAlphaQ,
  'alpha-s': mdiAlphaS,
  'alpha-y': mdiAlphaY,
  'archive': mdiArchive,
  'archive-arrow-down-outline': mdiArchiveArrowDownOutline,
  'archive-arrow-up': mdiArchiveArrowUp,
  'archive-arrow-up-outline': mdiArchiveArrowUpOutline,
  'archive-outline': mdiArchiveOutline,
  'arrange-bring-to-front': mdiArrangeBringToFront,
  'arrange-send-to-back': mdiArrangeSendToBack,
  'arrow-expand-horizontal': mdiArrowExpandHorizontal,
  'arrow-left': mdiArrowLeft,
  'arrow-right': mdiArrowRight,
  'asterisk': mdiAsterisk,
  'atom': mdiAtom,
  'auto-fix': mdiAutoFix,
  'backup-restore': mdiBackupRestore,
  'book': mdiBook,
  'book-open-page-variant': mdiBookOpenPageVariant,
  'book-open-variant': mdiBookOpenVariant,
  'brain': mdiBrain,
  'calendar': mdiCalendar,
  'calendar-alert': mdiCalendarAlert,
  'calendar-arrow-right': mdiCalendarArrowRight,
  'calendar-check': mdiCalendarCheck,
  'calendar-clock': mdiCalendarClock,
  'calendar-end': mdiCalendarEnd,
  'calendar-month': mdiCalendarMonth,
  'calendar-range': mdiCalendarRange,
  'calendar-start': mdiCalendarStart,
  'calendar-today': mdiCalendarToday,
  'call-made': mdiCallMade,
  'call-received': mdiCallReceived,
  'card-outline': mdiCardOutline,
  'card-plus-outline': mdiCardPlusOutline,
  'chart-bar': mdiChartBar,
  'chart-gantt': mdiChartGantt,
  'chart-pie': mdiChartPie,
  'check': mdiCheck,
  'checkbox-blank-outline': mdiCheckboxBlankOutline,
  'checkbox-marked-circle-outline': mdiCheckboxMarkedCircleOutline,
  'checkbox-marked-outline': mdiCheckboxMarkedOutline,
  'check-circle-outline': mdiCheckCircleOutline,
  'chevron-down': mdiChevronDown,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  'chevron-up': mdiChevronUp,
  'circle-outline': mdiCircleOutline,
  'circle-small': mdiCircleSmall,
  'clipboard-text-outline': mdiClipboardTextOutline,
  'clock-outline': mdiClockOutline,
  'close': mdiClose,
  'close-circle-outline': mdiCloseCircleOutline,
  'cloud-outline': mdiCloudOutline,
  'code-braces': mdiCodeBraces,
  'code-json': mdiCodeJson,
  'code-tags': mdiCodeTags,
  'cog': mdiCog,
  'cog-outline': mdiCogOutline,
  'comment-outline': mdiCommentOutline,
  'comment-text-outline': mdiCommentTextOutline,
  'connection': mdiConnection,
  'content-copy': mdiContentCopy,
  'content-duplicate': mdiContentDuplicate,
  'content-paste': mdiContentPaste,
  'crosshairs-gps': mdiCrosshairsGps,
  'cube-outline': mdiCubeOutline,
  'cursor-default-outline': mdiCursorDefaultOutline,
  'cursor-pointer': mdiCursorPointer,
  'database-outline': mdiDatabaseOutline,
  'database-refresh': mdiDatabaseRefresh,
  'delete': mdiDelete,
  'delete-forever-outline': mdiDeleteForeverOutline,
  'delete-outline': mdiDeleteOutline,
  'delete-sweep': mdiDeleteSweep,
  'distribute-horizontal-center': mdiDistributeHorizontalCenter,
  'distribute-vertical-center': mdiDistributeVerticalCenter,
  'dock-left': mdiDockLeft,
  'dock-right': mdiDockRight,
  'dock-top': mdiDockTop,
  'dots-horizontal': mdiDotsHorizontal,
  'dots-vertical': mdiDotsVertical,
  'download': mdiDownload,
  'drag': mdiDrag,
  'drag-vertical': mdiDragVertical,
  'emoticon-happy-outline': mdiEmoticonHappyOutline,
  'eraser-variant': mdiEraserVariant,
  'export': mdiExport,
  'eye': mdiEye,
  'eye-off': mdiEyeOff,
  'eye-outline': mdiEyeOutline,
  'feather': mdiFeather,
  'file-chart-outline': mdiFileChartOutline,
  'file-document-multiple-outline': mdiFileDocumentMultipleOutline,
  'file-document-outline': mdiFileDocumentOutline,
  'file-multiple': mdiFileMultiple,
  'file-tree': mdiFileTree,
  'file-tree-outline': mdiFileTreeOutline,
  'filter': mdiFilter,
  'filter-outline': mdiFilterOutline,
  'fingerprint': mdiFingerprint,
  'fit-to-screen': mdiFitToScreen,
  'folder-move-outline': mdiFolderMoveOutline,
  'folder-open-outline': mdiFolderOpenOutline,
  'folder-outline': mdiFolderOutline,
  'format-bold': mdiFormatBold,
  'format-header-pound': mdiFormatHeaderPound,
  'format-italic': mdiFormatItalic,
  'format-letter-case-upper': mdiFormatLetterCaseUpper,
  'format-list-bulleted': mdiFormatListBulleted,
  'format-list-checkbox': mdiFormatListCheckbox,
  'format-list-numbered': mdiFormatListNumbered,
  'format-list-numbered-rtl': mdiFormatListNumberedRtl,
  'format-quote-open': mdiFormatQuoteOpen,
  'format-strikethrough': mdiFormatStrikethrough,
  'format-text': mdiFormatText,
  'format-underline': mdiFormatUnderline,
  'fullscreen': mdiFullscreen,
  'graph-outline': mdiGraphOutline,
  'grid': mdiGrid,
  'group': mdiGroup,
  'heart-outline': mdiHeartOutline,
  'help-circle': mdiHelpCircle,
  'hexagon-outline': mdiHexagonOutline,
  'history': mdiHistory,
  'home': mdiHome,
  'icon': mdiShapeOutline,
  'identifier': mdiIdentifier,
  'image-outline': mdiImageOutline,
  'image-plus': mdiImagePlus,
  'import': mdiImport,
  'inbox': mdiInbox,
  'inbox-arrow-down': mdiInboxArrowDown,
  'lightbulb-on-outline': mdiLightbulbOnOutline,
  'link': mdiLink,
  'link-off': mdiLinkOff,
  'link-variant': mdiLinkVariant,
  'lock': mdiLock,
  'lock-open-outline': mdiLockOpenOutline,
  'lock-outline': mdiLockOutline,
  'logout': mdiLogout,
  'magnet': mdiMagnet,
  'magnify': mdiMagnify,
  'map': mdiMap,
  'map-outline': mdiMapOutline,
  'marker': mdiMarker,
  'menu': mdiMenu,
  'merge': mdiMerge,
  'minus': mdiMinus,
  'monitor': mdiMonitor,
  'music-note-outline': mdiMusicNoteOutline,
  'newspaper': mdiNewspaper,
  'note': mdiNote,
  'notebook-outline': mdiNotebookOutline,
  'note-text-outline': mdiNoteTextOutline,
  'numeric-1': mdiNumeric1,
  'numeric-2': mdiNumeric2,
  'numeric-3': mdiNumeric3,
  'numeric-9-plus': mdiNumeric9Plus,
  'open-in-app': mdiOpenInApp,
  'open-in-new': mdiOpenInNew,
  'palette': mdiPalette,
  'paperclip': mdiPaperclip,
  'parallelogram': mdiRectangleOutline,
  'pencil': mdiPencil,
  'pencil-outline': mdiPencilOutline,
  'pin': mdiPin,
  'pin-off': mdiPinOff,
  'pin-outline': mdiPinOutline,
  'plus': mdiPlus,
  'plus-box': mdiPlusBox,
  'plus-box-outline': mdiPlusBoxOutline,
  'presentation-play': mdiPresentationPlay,
  'qrcode': mdiQrcode,
  'rectangle-outline': mdiRectangleOutline,
  'redo': mdiRedo,
  'refresh': mdiRefresh,
  'reply': mdiReply,
  'restore': mdiRestore,
  'rhombus-outline': mdiRhombusOutline,
  'scale-balance': mdiScaleBalance,
  'school': mdiSchool,
  'select-all': mdiSelectAll,
  'send': mdiSend,
  'server-network': mdiServerNetwork,
  'set-all': mdiSetAll,
  'set-none': mdiSetNone,
  'shape-outline': mdiShapeOutline,
  'share-variant': mdiShareVariant,
  'share-variant-outline': mdiShareVariantOutline,
  'shuffle': mdiShuffle,
  'star': mdiStar,
  'star-outline': mdiStarOutline,
  'swap-horizontal': mdiSwapHorizontal,
  'sync': mdiSync,
  'table': mdiTable,
  'table-of-contents': mdiTableOfContents,
  'table-plus': mdiTablePlus,
  'tag': mdiTag,
  'tag-multiple': mdiTagMultiple,
  'tag-multiple-outline': mdiTagMultipleOutline,
  'tag-off': mdiTagOff,
  'tag-outline': mdiTagOutline,
  'target': mdiTarget,
  'text': mdiText,
  'text-box': mdiTextBox,
  'text-box-multiple-outline': mdiTextBoxMultipleOutline,
  'text-box-outline': mdiTextBoxOutline,
  'text-short': mdiTextShort,
  'timeline-clock-outline': mdiTimelineClockOutline,
  'trapezoid': mdiRectangleOutline,
  'trash-can': mdiTrashCan,
  'trash-can-outline': mdiTrashCanOutline,
  'tray-arrow-down': mdiTrayArrowDown,
  'triangle-outline': mdiTriangleOutline,
  'tune': mdiTune,
  'undo': mdiUndo,
  'ungroup': mdiUngroup,
  'vector-line': mdiVectorLine,
  'vector-polygon': mdiVectorPolygon,
  'view-column': mdiViewColumn,
  'view-compact': mdiViewCompact,
  'view-dashboard': mdiViewDashboard,
  'view-dashboard-outline': mdiViewDashboardOutline,
  'view-grid': mdiViewGrid,
  'view-headline': mdiViewHeadline,
  'weather-night': mdiWeatherNight,
  'weather-sunny': mdiWeatherSunny,
  'web': mdiWeb,
  'weight': mdiWeight,
  'white-balance-sunny': mdiWhiteBalanceSunny,
  'wifi': mdiWifi,
  'wifi-off': mdiWifiOff,
};
